name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit-dev=10.1
  - gxx_linux-64=7.3
  - jupyterlab=1.2
  - nccl=2.4
  - nodejs=12.13
  - openmpi=4.0
  - pip=19.3
  - python=3.6
  - pytorch=1.3
  - torchvision=0.4
  
